PUT http://localhost:3000/api/blogs/5f226a5b921f2621f4f618d7/comments
Content-Type: application/json

{
  "title": "A new blog",
  "author": "Johan Lindell",
  "url": "https://fullstackopen.com/en/part7/exercises_extending_the_bloglist",
  "likes": "0",
  "comments": ["a very good blog", "love it", "yayyyy", "send it"]
}